name: CI Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd client && npm install

      - name: Run ESLint
        run: cd client && npm run lint

      - name: Run tests
        run: cd client && npm test

      - name: Build project
        run: cd client && npm run build
